---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Create ansible_host_files directory 
      file:
        path: ../ansible_host_files
        state: directory
        #owner: PS868905
        #group: PS868905
        mode: 0775

    - name: Parse All Firewalls
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_all_firewalls.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/firewall.yml"
      run_once: true

    - name: Parse Catalyst
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_catalyst.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/catalyst.yml"
      run_once: true

    - name: Parse Embedded Gaia
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_embedded_gaia.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/firewall_embedded_gaia.yml"
      run_once: true

    - name: Parse Full Gaia
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_full_gaia.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/firewall_full_gaia.yml"
      run_once: true

    - name: Parse Nexus
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_nexus.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/nexus.yml"
      run_once: true

    - name: Parse Routers
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_router.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/router.yml"
      run_once: true

    - name: Parse All Autonomous WAP
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_wap.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/autonomous_wap.yml"
      run_once: true

    - name: Parse All WLC
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_wlc_aireos.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/airos_wlc.yml"
      run_once: true

    - name: Parse All WLC
      vars:
        csvfile: "{{ lookup('file', '/mnt/vol_cnetops/inventories/report_wlc_ios_xe.csv') }}"
      template:
        src: "./templates/hosts_file_template.j2"
        dest: "../ansible_host_files/iosxe_wlc.yml"
      run_once: true

# Lab Devices
# These tasks are required to generate the portion of the host files dedicated to lab devices

    - name: Insert LAB devices to firewall.yml
      blockinfile:
        path: ../ansible_host_files/firewall.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_firewall') }}"
        marker: "# This block generated by the contents of the file reports/lab_firewall"

    - name: Insert LAB devices to firewall_full_gaia.yml
      blockinfile:
        path: ../ansible_host_files/firewall_full_gaia.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_firewall') }}"
        marker: "# This block generated by the contents of the file reports/lab_firewall"

    - name: Insert LAB devices to firewall_embedded_gaia.yml
      blockinfile:
        path: ../ansible_host_files/firewall_embedded_gaia.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_firewall') }}"
        marker: "# This block generated by the contents of the file reports/lab_firewall"

    - name: Insert LAB devices to Catalyst
      blockinfile:
        path: ../ansible_host_files/catalyst.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_catalyst') }}"
        marker: "# This block generated by the contents of the file reports/lab_catalyst"
  
    - name: Insert LAB devices to Router
      blockinfile:
        path: ../ansible_host_files/router.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_router') }}"
        marker: "# This block generated by the contents of the file reports/lab_router"

    - name: Insert LAB devices to airos_wlc
      blockinfile:
        path: ../ansible_host_files/airos_wlc.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_airos_wlc') }}"
        marker: "# This block generated by the contents of the file reports/lab_airos_wlc"

    - name: Insert LAB devices to iosxe_wlc
      blockinfile:
        path: ../ansible_host_files/iosxe_wlc.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_iosxe_wlc') }}"
        marker: "# This block generated by the contents of the file reports/lab_airos_wlc"

    - name: Insert LAB devices to auto_wap
      blockinfile:
        path: ../ansible_host_files/autonomous_wap.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_auto_wap') }}"
        marker: "# This block generated by the contents of the file reports/lab_airos_wlc"

    - name: Insert LAB devices to nexus.yml
      blockinfile:
        path: ../ansible_host_files/nexus.yml
        insertafter: EOF
        block: "{{ lookup('file', './lab_files/lab_nexus') }}"
        marker: "# This block generated by the contents of the file reports/lab_nexus"